sonar.projectKey=pipeline
sonar.projectName=simple-python-app

# Lokasi source code yang mau di-scan
sonar.sources=.
sonar.exclusions=venv/**, tests/**, test_app.py

# Laporan unit test coverage
sonar.python.coverage.reportPaths=coverage.xml
